### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by ninng** [wensiqun/asmsupport#6]
try-catch 程序块里如果 catch 块超过一个就会报错
```
Exception in thread "main" java.lang.ClassCastException: cn.wensiqun.asmsupport.client.block.Catch$2 cannot be cast to cn.wensiqun.asmsupport.core.block.method.AbstractMethodBody
	at cn.wensiqun.asmsupport.core.block.KernelProgramBlock.getMethodBody(KernelProgramBlock.java:757)
	at cn.wensiqun.asmsupport.core.block.KernelProgramBlock.getMethod(KernelProgramBlock.java:949)
	at cn.wensiqun.asmsupport.core.block.KernelProgramBlock.getType(KernelProgramBlock.java:853)
	at cn.wensiqun.asmsupport.core.block.control.exception.KernelCatch.getExceptionType(KernelCatch.java:90)
	at cn.wensiqun.asmsupport.core.block.control.exception.ExceptionSerialBlock.appendEpisode(ExceptionSerialBlock.java:187)
	at cn.wensiqun.asmsupport.core.block.control.exception.KernelCatch.catch_(KernelCatch.java:72)
	at cn.wensiqun.asmsupport.client.block.Catch.catch_(Catch.java:59)
```

**Comment by wensiqun** [comment]
能给出你的测试代码样例吗？

**Comment by ninng** [comment]
@wensiqun 我用的只是文档里面的例子
```
DummyClass dc = new DummyClass().public_().name("Test");
    dc.newMethod("main").public_().static_().argTypes(String[].class).body(
        new MethodBody() {
          @Override
          public void body(LocVar... args) {

            try_(new Try() {
              @Override
              public void body() {
                //Do try branch.
              }
            }).catch_(new Catch(RuntimeException.class) {
              @Override
              public void body(LocVar e) {
                //Do catch block
              }
            }).catch_(new Catch(Exception.class) {
              @Override
              public void body(LocVar e) {
                //Do catch block
              }
            });
            return_();
          }
        }
    );
    dc.build();
  }
```

**Comment by wensiqun** [comment]
是个BUG，感谢支持和使用。
